/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Account.Account;
import Business.Account.EmployeeAccount;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ITEnterprise;
import Business.Network.Network;
import UserInterface.SystemAdmin.SystemAdminMainJFrame;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author jxw
 */
public class NetworkJPanel extends javax.swing.JPanel {
    EcoSystem system;
    private Network selectedNetwork = null;
    private String selectedCategory = "";
    private Enterprise selectedEnterprise = null;
    private EmployeeAccount employeeAccount;

    /**
     * Creates new form NetworkJPanel
     */
    public NetworkJPanel(EcoSystem system, EmployeeAccount employeeAccount) {
        initComponents();
        this.system = system;
        this.employeeAccount = employeeAccount;
        // Manage System Panel
        populateNetworkList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkList = new javax.swing.JList<>();
        createNetworkButton = new javax.swing.JButton();
        editNetworkButton = new javax.swing.JButton();
        removeNetworkButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        typeList = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        enterpriseList = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        createEnterpriseBtn = new javax.swing.JButton();
        editEnterpriseBtn = new javax.swing.JButton();
        removeEnterpriseBtn = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("Network");

        networkList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        networkList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                networkListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(networkList);

        createNetworkButton.setText("Create Network");
        createNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNetworkButtonActionPerformed(evt);
            }
        });

        editNetworkButton.setText("Edit Network");
        editNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNetworkButtonActionPerformed(evt);
            }
        });

        removeNetworkButton.setText("Remove Network");
        removeNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeNetworkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createNetworkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeNetworkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editNetworkButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createNetworkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editNetworkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeNetworkButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        typeList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        typeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeListMouseClicked(evt);
            }
        });
        typeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                typeListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(typeList);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel17.setText("Enterprise Type");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enterpriseList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        enterpriseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                enterpriseListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(enterpriseList);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel18.setText("Enterprise");

        createEnterpriseBtn.setText("Create Enterprise");
        createEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseBtnActionPerformed(evt);
            }
        });

        editEnterpriseBtn.setText("Edit Enterprise");
        editEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEnterpriseBtnActionPerformed(evt);
            }
        });

        removeEnterpriseBtn.setText("Remove Enterprise");
        removeEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnterpriseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeEnterpriseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createEnterpriseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editEnterpriseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createEnterpriseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editEnterpriseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeEnterpriseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_networkListMouseClicked
        populateTypeList();

        editNetworkButton.setEnabled(true);
    }//GEN-LAST:event_networkListMouseClicked

    private void createNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNetworkButtonActionPerformed
        CreateNetworkJFrame f = new CreateNetworkJFrame(system, selectedNetwork, this, "Create");
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_createNetworkButtonActionPerformed

    private void editNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNetworkButtonActionPerformed
        CreateNetworkJFrame f = new CreateNetworkJFrame(system, selectedNetwork, this, "edit");
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_editNetworkButtonActionPerformed

    private void removeNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeNetworkButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure to remove this network from the system?");
        if (choice == 0) {
            system.removeNetwork(selectedNetwork);
            selectedNetwork = null;
            DB4OUtil.getInstance().storeSystem(system);

            resetAllLists();
        }
    }//GEN-LAST:event_removeNetworkButtonActionPerformed

    private void typeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_typeListMouseClicked

    private void enterpriseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_enterpriseListValueChanged
        selectedEnterprise = (Enterprise) enterpriseList.getSelectedValue();

        createEnterpriseBtn.setEnabled(true);
        removeEnterpriseBtn.setEnabled(true);
        editEnterpriseBtn.setEnabled(true);
    }//GEN-LAST:event_enterpriseListValueChanged

    private void editEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEnterpriseBtnActionPerformed
        if (enterpriseList.getSelectedValue() != null) {
            SystemAdminMainJFrame f = new SystemAdminMainJFrame(system, this.selectedNetwork,selectedEnterprise, this.selectedCategory, this.employeeAccount, null, null);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            
        }
    }//GEN-LAST:event_editEnterpriseBtnActionPerformed

    private void typeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_typeListValueChanged
        populateEnterpriseList();
    }//GEN-LAST:event_typeListValueChanged

    private void removeEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnterpriseBtnActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure to remove this enterprise from the system?");
        if (choice == 0) {
            this.selectedNetwork.getEnterpriseDirectory().removeEnterprise(selectedEnterprise);
            DB4OUtil.getInstance().storeSystem(system);

            populateEnterpriseList();
        }
    }//GEN-LAST:event_removeEnterpriseBtnActionPerformed

    private void createEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseBtnActionPerformed
        String type = typeList.getSelectedValue();
        CreateEnterpriseJFrame ceJFrame = new CreateEnterpriseJFrame(system, this, type, selectedNetwork);
        ceJFrame.setLocationRelativeTo(this);
        ceJFrame.setVisible(true);
    }//GEN-LAST:event_createEnterpriseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEnterpriseBtn;
    private javax.swing.JButton createNetworkButton;
    private javax.swing.JButton editEnterpriseBtn;
    private javax.swing.JButton editNetworkButton;
    private javax.swing.JList<Enterprise> enterpriseList;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> networkList;
    private javax.swing.JButton removeEnterpriseBtn;
    private javax.swing.JButton removeNetworkButton;
    private javax.swing.JList<String> typeList;
    // End of variables declaration//GEN-END:variables
    private void populateNetworkList() {
        //== networkList
        DefaultListCellRenderer renderer1 = (DefaultListCellRenderer) networkList.getCellRenderer();
        renderer1.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultListModel<String> networkModel = new DefaultListModel<>();
        for (Network net : system.getNetworkList()) {
            networkModel.addElement(net.getstate());
        }
        networkList.setModel(networkModel);

        editNetworkButton.setEnabled(false);
        
    }
    private void populateTypeList() {
        
        
        int index = networkList.getSelectedIndex();
        if (index >= 0) {
            DefaultListModel<Enterprise> enterpriseModel = new DefaultListModel<>();
            enterpriseList.setModel(enterpriseModel);

            String selected = (String) networkList.getSelectedValue();
            selectedNetwork = system.getNetworkByState(selected);

            //== Enterprise Category 
            DefaultListCellRenderer renderer2 = (DefaultListCellRenderer) typeList.getCellRenderer();
            renderer2.setHorizontalAlignment(SwingConstants.CENTER);
            DefaultListModel<String> categoryModel = new DefaultListModel<>();
            categoryModel.addElement("Exam Enterprise");
            categoryModel.addElement("IT");
            categoryModel.addElement("Bank");
            
            typeList.setModel(categoryModel);

            createEnterpriseBtn.setEnabled(false);
            removeEnterpriseBtn.setEnabled(false);
            editEnterpriseBtn.setEnabled(false);
        
        }
    }

    void resetAllLists() {
        DefaultListModel<Enterprise> enterpriseModel = new DefaultListModel<>();
        enterpriseList.setModel(enterpriseModel);
        DefaultListModel<String> typeModel = new DefaultListModel<>();
        typeList.setModel(typeModel);
        populateNetworkList();
    }

    private void populateEnterpriseList() {
        if (typeList.getSelectedValue() != null) {
            selectedCategory = typeList.getSelectedValue();
            DefaultListCellRenderer renderer3 = (DefaultListCellRenderer) enterpriseList.getCellRenderer();
            renderer3.setHorizontalAlignment(SwingConstants.CENTER);
            DefaultListModel<Enterprise> enterpriseModel = new DefaultListModel<>();

            //add Test Center
            if (selectedCategory.equalsIgnoreCase("Exam Enterprise")) {
                for (Enterprise en : selectedNetwork.getExamEnterpriseList()) {
                    enterpriseModel.addElement(en);
                }
            }

            if (selectedCategory.equalsIgnoreCase("IT")) {
                
                for (Enterprise en : selectedNetwork.getITEnterpriseList()) {
                    enterpriseModel.addElement(en);
                }
            }
            
            if (selectedCategory.equalsIgnoreCase("Bank")) {
                for (Enterprise en : selectedNetwork.getBankEnterpriseList()) {
                    enterpriseModel.addElement(en);
                }
                
            }
            
            enterpriseList.setModel(enterpriseModel);
        }
        createEnterpriseBtn.setEnabled(true);
        removeEnterpriseBtn.setEnabled(false);
        editEnterpriseBtn.setEnabled(false);
    }
}
