/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Account.ApplicantAccount;
import Business.Account.EmployeeAccount;
import Business.EcoSystem;
import Business.Enterprise.BankEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ExamEnterprise.ExamEnterprise;
import Business.Enterprise.ITEnterprise;
import Business.Network.Network;
import Business.Role.SystemManagerRole;

import UserInterface.Manager.NewManagerMainJPanel;
import UserInterface.SystemAdmin.SystemAdminMainJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author jxw
 */
public class SystemAdminMainJFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private Network selectedNetwork;
    private Enterprise selectedEnterprise;
    private String selectedCategory;
    private EmployeeAccount employeeAccount;

    /**
     * Creates new form SystemAdminMainJFrame
     */
    public SystemAdminMainJFrame() {
        initComponents();
    }

    SystemAdminMainJFrame(EcoSystem system, Network selectedNetwork, Enterprise selectedEnterprise, String selectedCategory, EmployeeAccount employeeAccount, ApplicantAccount applicantAccount,
            SystemAdminMainJPanel panel) {
        initComponents();
        this.setSize (1050, 650);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        if (selectedEnterprise instanceof ITEnterprise) {
            NewManagerMainJPanel cp = new NewManagerMainJPanel(system, selectedNetwork, this.jPanel1, selectedEnterprise, employeeAccount, this, new SystemManagerRole());
            this.jPanel1.add(cp);
        }
        if (selectedEnterprise instanceof BankEnterprise) {
            NewManagerMainJPanel cp = new NewManagerMainJPanel(system, selectedNetwork, this.jPanel1, selectedEnterprise, employeeAccount, this, new SystemManagerRole());
            this.jPanel1.add(cp);
        }

        if (selectedEnterprise instanceof ExamEnterprise) {
            NewManagerMainJPanel cp = new NewManagerMainJPanel(system, this.selectedNetwork, this.jPanel1, selectedEnterprise, employeeAccount, this, new SystemManagerRole());
            this.jPanel1.add(cp);
        }

        if (selectedEnterprise == null) {
            JOptionPane.showMessageDialog(null, "Enterprise not selected.");
        }
        CardLayout layout = (CardLayout) this.jPanel1.getLayout();
        layout.next(this.jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 650));
        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SystemAdminMainJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
