/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Manager;

import Business.Account.EmployeeAccount;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Job.FullTimeJob;
import Business.Job.InternshipJob;
import Business.Job.Job;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 11638
 */
public class ManageJobJPanel extends javax.swing.JPanel {
    
    private Enterprise en;
    private EmployeeAccount account;
    private EcoSystem system;
    private Employee employee;
    
    /**
     * Creates new form ManageJobJPanel
     */
    public ManageJobJPanel(EcoSystem system, Enterprise en, EmployeeAccount userAccount) {
        initComponents();
        this.system = system;
        this.en = en;
        this.account = userAccount;
        this.employee = account.getEmployee();
        populateJobTable();
    }

    public void populateJobTable() {
        DefaultTableModel dtm = (DefaultTableModel) jobTable.getModel();
        dtm.setRowCount(0);

        for (Job job : en.getHireFullTimeJobs()) {
            Object[] row = new Object[4];
            row[0] = job;
            row[1] = "Full Time Job";
            row[2] = job.getRequirement();
            row[3] = job.getIssuer();
            dtm.addRow(row);
        }            
        
        for (Job job : en.getHireInternJobs()) {
            Object[] row = new Object[4];
            row[0] = job;
            row[1] = "Internship Job";
            row[2] = job.getRequirement();
            row[3] = job.getIssuer();
            dtm.addRow(row);
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jobTable = new javax.swing.JTable();
        addInterBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addFullTimeBtn = new javax.swing.JButton();

        jobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Job", "Type", "Requirment", "Creator"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jobTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jobTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jobTable);

        addInterBtn.setText("Add Internship");
        addInterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInterBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Job");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        addFullTimeBtn.setText("Add Full Time Job");
        addFullTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFullTimeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addInterBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFullTimeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(addInterBtn)
                    .addComponent(addFullTimeBtn))
                .addContainerGap(329, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jobTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jobTableMouseClicked

    private void addInterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInterBtnActionPerformed
        // TODO add your handling code here:
        InternshipJob internshipJob = new InternshipJob("", "", employee, en);
        en.addInterns(internshipJob);
        InternFrame inter = new InternFrame (system, en, internshipJob, this);
        inter.setLocationRelativeTo(null);
        inter.setVisible(true);
        DB4OUtil.getInstance().storeSystem(system);
        populateJobTable();
    }//GEN-LAST:event_addInterBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int index = jobTable.getSelectedRow();
        TableModel model = jobTable.getModel();
        if (index >= 0) {
//            EmployeeAccount hr = (EmployeeAccount) model.getValueAt(index, 1);            
//            en.getAccountDir().removeAccount(account);
            Job job = (Job) model.getValueAt(index, 0);
            if (en.getHireFullTimeJobs().contains(job)) {
                en.getHireFullTimeJobs().remove(job);
            } else if (en.getHireInternJobs().contains(job)) {
                en.getHireInternJobs().remove(job);                
            }
            populateJobTable();
            DB4OUtil.getInstance().storeSystem(system);
        } else {
            JOptionPane.showMessageDialog(null, "Please choose the Job");
            return;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addFullTimeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFullTimeBtnActionPerformed
        // TODO add your handling code here:
        FullTimeJob fullTimeJob = new FullTimeJob("", "", employee, en);
        en.addFullTimes(fullTimeJob);
        FullTimeFrame fullTime = new FullTimeFrame(system, en, fullTimeJob, this);
        fullTime.setLocationRelativeTo(null);
        fullTime.setVisible(true);
        DB4OUtil.getInstance().storeSystem(system);
        populateJobTable();
    }//GEN-LAST:event_addFullTimeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFullTimeBtn;
    private javax.swing.JButton addInterBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jobTable;
    // End of variables declaration//GEN-END:variables
}
