/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Manager;

import Business.Account.EmployeeAccount;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ExamEnterprise.ExamEnterprise;
import Business.Network.Network;
import Business.Role.Role;
import Business.Role.RoleType;
import UserInterface.LoginJFrame;
import java.awt.Color;
import java.awt.Label;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author 11638
 */
public class NewManagerMainJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel container;
    private Enterprise en;
    private EmployeeAccount account;
    private JFrame frame;
    private Role role;
    private Employee employee;
    private Network network;
    
    private ProfileJPanel profileJPanel;
    private ChangePasswordJPanel changePasswordJPanel;
    private ManageJobJPanel manageJobJPanel;
    private ManageApplicantJPanel manageApplicantJPanel;
    private CompanyInfoJPanel companyInfoJPanel;
    private ManageEmployeeJPanel manageEmployeeJPanel;
    private ReviewJPanel reviewJPanel;
    private TestJPanel testJPanel;
    
    /**
     * Creates new form NewManagerMainJPanel
     */
    public NewManagerMainJPanel(EcoSystem system, Network network, JPanel container, Enterprise en, EmployeeAccount userAccount, 
            JFrame frame, Role role) {
        initComponents();
        this.system = system;
        this.container = container;
        this.en = en;
        this.network = network;
        this.account = (EmployeeAccount) userAccount;
        this.frame = frame;
        this.employee = this.account.getEmployee();
        this.role = role;
        
        if (en instanceof ExamEnterprise) {
            applicantLb.setVisible(false);
            applicantLb.setEnabled(false);
            jobLb.setEnabled(false);
            jobLb.setVisible(false);
            applicantLb.setEnabled(false);
            applicantLb.setVisible(false);
            employeeLb.setVisible(false);
            employeeLb.setEnabled(false);
            reviewLb.setEnabled(false);
            reviewLb.setVisible(false);
        } else {
            testLb.setVisible(false);
            testLb.setEnabled(false);
        }
        
        if (role.getRoleType().equals(RoleType.HR)) {
            employeeLb.setVisible(false);
            employeeLb.setEnabled(false);
        }
        
        if(role.getRoleType().equals(RoleType.SystemManager)){
            logoutLb.setVisible(false);
            logoutLb.setEnabled(false);

        }
        
        nameLabel.setText(userAccount.getUsername());
        
        profileJPanel = new ProfileJPanel(system, container, en, userAccount, frame, role);
        changePasswordJPanel = new ChangePasswordJPanel(system, account);
        manageJobJPanel = new ManageJobJPanel(system, en, userAccount);
        manageApplicantJPanel = new ManageApplicantJPanel(system, network, en, userAccount);
        
        manageEmployeeJPanel = new ManageEmployeeJPanel(system, account, en, role);
        reviewJPanel = new ReviewJPanel(en, account);
        testJPanel = new TestJPanel(system, en);
        
        changeColor(profileLb);
        jSplitPane1.setRightComponent (profileJPanel);
    }

    private void changeColor (JLabel label) {
        profileLb.setForeground(Color.GRAY);
        jobLb.setForeground(Color.GRAY);
        passwordLb.setForeground(Color.GRAY);
        applicantLb.setForeground(Color.GRAY);
        companyLb.setForeground(Color.GRAY);
        employeeLb.setForeground(Color.GRAY);
        testLb.setForeground(Color.GRAY);
        reviewLb.setForeground(Color.GRAY);
        logoutLb.setForeground(Color.GRAY);
        
        label.setForeground(Color.WHITE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        profileLb = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jobLb = new javax.swing.JLabel();
        passwordLb = new javax.swing.JLabel();
        applicantLb = new javax.swing.JLabel();
        companyLb = new javax.swing.JLabel();
        employeeLb = new javax.swing.JLabel();
        testLb = new javax.swing.JLabel();
        reviewLb = new javax.swing.JLabel();
        logoutLb = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(300);

        leftPanel.setBackground(new java.awt.Color(54, 33, 89));

        profileLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        profileLb.setForeground(new java.awt.Color(255, 255, 255));
        profileLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Profile_32px.png"))); // NOI18N
        profileLb.setText("Profile");
        profileLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLbMouseClicked(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("<Name>");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome, ");

        jobLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jobLb.setForeground(new java.awt.Color(255, 255, 255));
        jobLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Job_32px.png"))); // NOI18N
        jobLb.setText("Manage Job");
        jobLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobLbMouseClicked(evt);
            }
        });

        passwordLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        passwordLb.setForeground(new java.awt.Color(255, 255, 255));
        passwordLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Password_32px.png"))); // NOI18N
        passwordLb.setText("Change Password");
        passwordLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordLbMouseClicked(evt);
            }
        });

        applicantLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        applicantLb.setForeground(new java.awt.Color(255, 255, 255));
        applicantLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Submit_Resume_32px.png"))); // NOI18N
        applicantLb.setText("Manage Applicant");
        applicantLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applicantLbMouseClicked(evt);
            }
        });

        companyLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        companyLb.setForeground(new java.awt.Color(255, 255, 255));
        companyLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Management_32px.png"))); // NOI18N
        companyLb.setText("Company Infomation");
        companyLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyLbMouseClicked(evt);
            }
        });

        employeeLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        employeeLb.setForeground(new java.awt.Color(255, 255, 255));
        employeeLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Name_Tag_32px.png"))); // NOI18N
        employeeLb.setText("Manage Employee");
        employeeLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeLbMouseClicked(evt);
            }
        });

        testLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        testLb.setForeground(new java.awt.Color(255, 255, 255));
        testLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Test_Passed_32px.png"))); // NOI18N
        testLb.setText("Test");
        testLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testLbMouseClicked(evt);
            }
        });

        reviewLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        reviewLb.setForeground(new java.awt.Color(255, 255, 255));
        reviewLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Submit_Resume_32px.png"))); // NOI18N
        reviewLb.setText("Review");
        reviewLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewLbMouseClicked(evt);
            }
        });

        logoutLb.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        logoutLb.setForeground(new java.awt.Color(255, 255, 255));
        logoutLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Close_Window_32px.png"))); // NOI18N
        logoutLb.setText("Log Out");
        logoutLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(testLb, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLb, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reviewLb, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeLb)
                            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(applicantLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(jobLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(companyLb, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameLabel))
                .addGap(28, 28, 28)
                .addComponent(profileLb)
                .addGap(35, 35, 35)
                .addComponent(passwordLb)
                .addGap(40, 40, 40)
                .addComponent(jobLb)
                .addGap(39, 39, 39)
                .addComponent(applicantLb)
                .addGap(38, 38, 38)
                .addComponent(companyLb)
                .addGap(38, 38, 38)
                .addComponent(reviewLb)
                .addGap(39, 39, 39)
                .addComponent(employeeLb)
                .addGap(38, 38, 38)
                .addComponent(testLb)
                .addGap(38, 38, 38)
                .addComponent(logoutLb)
                .addGap(265, 265, 265))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jSplitPane1)
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void profileLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLbMouseClicked
        changeColor(profileLb);
        
        jSplitPane1.setRightComponent(profileJPanel);
    }//GEN-LAST:event_profileLbMouseClicked

    
    private void jobLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobLbMouseClicked
        // TODO add your handling code here:
        changeColor(jobLb);
        
        jSplitPane1.setRightComponent(manageJobJPanel);
    }//GEN-LAST:event_jobLbMouseClicked

    private void passwordLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordLbMouseClicked
        // TODO add your handling code here:
        changeColor(passwordLb);
        
        jSplitPane1.setRightComponent(changePasswordJPanel);
    }//GEN-LAST:event_passwordLbMouseClicked

    private void applicantLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicantLbMouseClicked
        // TODO add your handling code here:
        changeColor(applicantLb);
        
        jSplitPane1.setRightComponent(manageApplicantJPanel);
    }//GEN-LAST:event_applicantLbMouseClicked

    private void companyLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyLbMouseClicked
        // TODO add your handling code here:
        changeColor(companyLb);
        companyInfoJPanel = new CompanyInfoJPanel(system, en);
        jSplitPane1.setRightComponent(companyInfoJPanel);
    }//GEN-LAST:event_companyLbMouseClicked

    private void employeeLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeLbMouseClicked
        // TODO add your handling code here:
        changeColor(employeeLb);
        
        jSplitPane1.setRightComponent(manageEmployeeJPanel);
    }//GEN-LAST:event_employeeLbMouseClicked

    private void testLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testLbMouseClicked
        // TODO add your handling code here:
        changeColor(testLb);
        
        jSplitPane1.setRightComponent(testJPanel);
    }//GEN-LAST:event_testLbMouseClicked

    private void reviewLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewLbMouseClicked
        // TODO add your handling code here:
        changeColor(reviewLb);
        
        jSplitPane1.setRightComponent(reviewJPanel);
    }//GEN-LAST:event_reviewLbMouseClicked

    private void logoutLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLbMouseClicked
        // TODO add your handling code here:
        LoginJFrame lf = new LoginJFrame();
        this.frame.dispose();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_logoutLbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicantLb;
    private javax.swing.JLabel companyLb;
    private javax.swing.JLabel employeeLb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel jobLb;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logoutLb;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLb;
    private javax.swing.JLabel profileLb;
    private javax.swing.JLabel reviewLb;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel testLb;
    // End of variables declaration//GEN-END:variables
}
