/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Manager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.ExamRequest;
import Business.WorkQueue.ExamStatus;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 11638
 */
public class TestJPanel extends javax.swing.JPanel {

    EcoSystem system;
    Enterprise enterprise;
    
    /**
     * Creates new form TestJPanel
     */
    public TestJPanel(EcoSystem system, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.enterprise = enterprise;
        populateExamTable();
    }
   
    public void populateExamTable () {
        DefaultTableModel dtm = (DefaultTableModel) examTable.getModel();
        dtm.setRowCount(0);
        
        for (WorkRequest request : enterprise.getWorkQ().getWorkRequests()) {
            if (request instanceof ExamRequest) {
                ExamRequest er = (ExamRequest) request;
                Object[] row = new Object[4];
                row[0] = er;
                row[1] = er.getAccount().getApplicant();
                row[2] = er.getExamStatus();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        examTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();

        examTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        examTable.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        examTable.setForeground(new java.awt.Color(51, 51, 51));
        examTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Applicant", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        examTable.setGridColor(new java.awt.Color(240, 240, 240));
        examTable.setRowHeight(40);
        examTable.setSelectionBackground(new java.awt.Color(96, 83, 150));
        examTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(examTable);
        if (examTable.getColumnModel().getColumnCount() > 0) {
            examTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            examTable.getColumnModel().getColumn(1).setPreferredWidth(20);
            examTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Exam List");

        editBtn.setBackground(new java.awt.Color(36, 193, 93));
        editBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 51, 51));
        editBtn.setText("Edit Test Result");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(54, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void examTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examTableMouseClicked

    }//GEN-LAST:event_examTableMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int index = examTable.getSelectedRow();
        if (index >= 0) {
    
            ExamRequest selectedRequest = (ExamRequest) examTable.getValueAt (index, 0);
            if(selectedRequest.getExamStatus().equals(ExamStatus.ExamAccepted)){
                EditTestResultJFrame editTestResultJFrame = new EditTestResultJFrame(system, selectedRequest.getAccount().getApplicant(), selectedRequest, this);
                editTestResultJFrame.setLocationRelativeTo(null);
                editTestResultJFrame.setVisible(true);
            }else if(selectedRequest.getExamStatus().equals(ExamStatus.Ready)){
                JOptionPane.showMessageDialog(null, "Applicants should accept the test first!");
            }else{
                JOptionPane.showMessageDialog(null, "Cannot edit test now!");
            }
                                
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBtn;
    private javax.swing.JTable examTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
