/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Applicant;

import Business.Account.ApplicantAccount;
import Business.Applicant.Applicant;
import Business.EcoSystem;
import Business.Role.Role;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author 11638
 */
public class ApplicantProfileJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private ApplicantAccount account;
    private Applicant applicant;
    private Role accessRole;
    private BasicJPanel basicJPanel;
    private ChangePasswordJPanel changeJPanel;
    private ResumeJPanel resumeJPanel;
    
    /**
     * Creates new form ApplicantProfileJPanel
     */
    public ApplicantProfileJPanel(EcoSystem system, ApplicantAccount account, Role accessRole) {
        initComponents();
        this.system = system;
        this.account = account;
        this.accessRole = accessRole;
        
        this.basicJPanel = new BasicJPanel(system, account, accessRole);
        this.changeJPanel = new ChangePasswordJPanel(system, account, accessRole);
        this.resumeJPanel = new ResumeJPanel(system, account, accessRole);
        
        jSplitPane2.setBottomComponent(basicJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        lbPatient = new javax.swing.JLabel();
        lbDoctor = new javax.swing.JLabel();
        lbPharmacy = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1050, 900));
        setRequestFocusEnabled(false);

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));

        lbPatient.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        lbPatient.setText("Account Info");
        lbPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPatientMouseClicked(evt);
            }
        });

        lbDoctor.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        lbDoctor.setForeground(new java.awt.Color(128, 128, 128));
        lbDoctor.setText("Change Password");
        lbDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDoctorMouseClicked(evt);
            }
        });

        lbPharmacy.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        lbPharmacy.setForeground(new java.awt.Color(128, 128, 128));
        lbPharmacy.setText("Resume");
        lbPharmacy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPharmacyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(lbPatient)
                .addGap(112, 112, 112)
                .addComponent(lbDoctor)
                .addGap(118, 118, 118)
                .addComponent(lbPharmacy)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPharmacy)
                    .addComponent(lbDoctor)
                    .addComponent(lbPatient))
                .addGap(29, 29, 29))
        );

        jSplitPane2.setTopComponent(topPanel);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setPreferredSize(new java.awt.Dimension(1060, 693));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPatientMouseClicked
        // TODO add your handling code here:
        lbPatient.setForeground(Color.BLACK);
        lbDoctor.setForeground(Color.GRAY);
        lbPharmacy.setForeground(Color.GRAY);

        jSplitPane2.setBottomComponent(basicJPanel);
    }//GEN-LAST:event_lbPatientMouseClicked

    private void lbDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDoctorMouseClicked
        // TODO add your handling code here:
        lbPatient.setForeground(Color.GRAY);
        lbDoctor.setForeground(Color.BLACK);
        lbPharmacy.setForeground(Color.GRAY);

        jSplitPane2.setBottomComponent(changeJPanel);
    }//GEN-LAST:event_lbDoctorMouseClicked

    private void lbPharmacyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPharmacyMouseClicked
        // TODO add your handling code here:
        lbPatient.setForeground(Color.GRAY);
        lbDoctor.setForeground(Color.GRAY);
        lbPharmacy.setForeground(Color.BLACK);

        jSplitPane2.setBottomComponent(resumeJPanel);
    }//GEN-LAST:event_lbPharmacyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lbDoctor;
    private javax.swing.JLabel lbPatient;
    private javax.swing.JLabel lbPharmacy;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
