/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Applicant;

import Business.Account.Account;
import Business.Account.ApplicantAccount;
import Business.EcoSystem;
import Business.Role.Role;
import java.awt.Color;

/**
 *
 * @author 11638
 */
public class ApplicationMainJPanel extends javax.swing.JPanel {
    
    ApplicationJPanel applicationJPanel;
    EcoSystem system;
    ApplicantAccount account;
    ResumeJPanel resumeJPanel;
    
    /**
     * Creates new form ApplicationMainJPanel
     */
    public ApplicationMainJPanel(EcoSystem system, ApplicantAccount account, Role accessRole) {
        initComponents();
        this.system = system;
        this.account = account;
        this.applicationJPanel = new ApplicationJPanel(system, account, accessRole);
        this.resumeJPanel = new ResumeJPanel(system, account, accessRole);
        
        if (account.getApplicant().getResume().getEducationResume().getSchool().equals("")) {
            Applicationlb.setForeground(Color.GRAY);
            Resumelb.setForeground(Color.BLACK);
            jSplitPane.setBottomComponent(resumeJPanel);
        } else {
            Applicationlb.setForeground(Color.BLACK);
            Resumelb.setForeground(Color.GRAY);
            jSplitPane.setBottomComponent(applicationJPanel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        topPanel1 = new javax.swing.JPanel();
        Applicationlb = new javax.swing.JLabel();
        Resumelb = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane.setDividerLocation(200);
        jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Applicationlb.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        Applicationlb.setText("Application List");
        Applicationlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApplicationlbMouseClicked(evt);
            }
        });

        Resumelb.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        Resumelb.setForeground(new java.awt.Color(128, 128, 128));
        Resumelb.setText("Resume");
        Resumelb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResumelbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanel1Layout = new javax.swing.GroupLayout(topPanel1);
        topPanel1.setLayout(topPanel1Layout);
        topPanel1Layout.setHorizontalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(Applicationlb, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Resumelb)
                .addGap(245, 245, 245))
        );
        topPanel1Layout.setVerticalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resumelb)
                    .addComponent(Applicationlb))
                .addGap(29, 29, 29))
        );

        jSplitPane.setTopComponent(topPanel1);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setPreferredSize(new java.awt.Dimension(1060, 693));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(bottomPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ApplicationlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplicationlbMouseClicked
        // TODO add your handling code here:
        Applicationlb.setForeground(Color.BLACK);
        Resumelb.setForeground(Color.GRAY);

        jSplitPane.setBottomComponent(applicationJPanel);
    }//GEN-LAST:event_ApplicationlbMouseClicked

    private void ResumelbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumelbMouseClicked
        // TODO add your handling code here:
        Applicationlb.setForeground(Color.GRAY);
        Resumelb.setForeground(Color.BLACK);

        jSplitPane.setBottomComponent(resumeJPanel);
    }//GEN-LAST:event_ResumelbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Applicationlb;
    private javax.swing.JLabel Resumelb;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables
}
