/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Applicant;

import Business.Account.ApplicantAccount;
import Business.EcoSystem;
import Business.Exam.ExamOrder;
import Business.Network.Network;
import Business.Role.Role;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 11638
 */
public class ExamListJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private ApplicantAccount account;
    private Network net;
    
    
    /**
     * Creates new form ExamListJPanel
     */
    public ExamListJPanel(EcoSystem system, ApplicantAccount account, Network net, Role accessRole) {
        initComponents();
        this.system = system;
        this.account = account;
        this.net = net;
        populateTable();
        startButton.setEnabled(false);
        cancelButton.setEnabled(false);
        populateTable();
    }
    
    private void populateTable () {
        DefaultTableModel dtm = (DefaultTableModel) ExamTable.getModel();
        dtm.setRowCount(0);
        ArrayList<ExamOrder> list = account.getApplicant().getExamOrderDir().getExamOrderList();

        for (ExamOrder exam : list) {
            Object[] row = new Object[3];
            row[0] = exam;
            row[1] = exam.getQuestionCount();
            row[2] = exam.getStatus();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExamTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Exam List");

        ExamTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ExamTable.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        ExamTable.setForeground(new java.awt.Color(51, 51, 51));
        ExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Exam", "Exam Enterprise", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ExamTable.setGridColor(new java.awt.Color(240, 240, 240));
        ExamTable.setRowHeight(40);
        ExamTable.setSelectionBackground(new java.awt.Color(96, 83, 150));
        ExamTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExamTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ExamTable);

        cancelButton.setBackground(new java.awt.Color(36, 193, 93));
        cancelButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        cancelButton.setText("Cancel Exam");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        startButton.setBackground(new java.awt.Color(36, 193, 93));
        startButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        startButton.setText("Start Exam");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(cancelButton))
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExamTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExamTableMouseClicked
        startButton.setEnabled(true);
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_ExamTableMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = ExamTable.getSelectedColumn();
        if (selectedRow >= 0) {
            ExamOrder exam = (ExamOrder) ExamTable.getValueAt(selectedRow, 0);
            this.account.getApplicant().getExamOrderDir().getExamOrderList().remove(exam);
        }
        populateTable();
        cancelButton.setEnabled(false);
        startButton.setEnabled(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        int selectedRow = ExamTable.getSelectedColumn();
        if (selectedRow >= 0) {
            ExamOrder exam = (ExamOrder) ExamTable.getValueAt(selectedRow, 0);
        }
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ExamTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
