/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Applicant;

import Business.Account.ApplicantAccount;
import Business.EcoSystem;
import Business.Job.JobType;
import Business.Network.Network;
import Business.Role.Role;
import UserInterface.LoginJFrame;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author 11638
 */
public class MainFrame extends javax.swing.JFrame {
    
    private EcoSystem system;
    private ApplicantAccount account;
    private Network net;
    private JobType type;
    
    /**
     * Creates new form Home
     */
    public MainFrame(EcoSystem system, Network net, ApplicantAccount account, JobType type, Role accessRole) {
        initComponents();
        this.system = system;
        this.net = net;
        this.account = account;
        this.type = type;
        setSize(1500, 900);
        myInit();
    }

    private void myInit () {
        areaLabel.setText(net.getstate());
        nameLabel.setText(account.getApplicant().getFirstName());
        typeLabel.setText(type.getValue());
        
        ApplicantProfileJPanel profileJPanel = new ApplicantProfileJPanel(system, account, account.getRole());
        jSplitPane1.setRightComponent(profileJPanel);        
        
        lbCreate.setForeground(Color.WHITE);
        lbView.setForeground(Color.GRAY);
        lbRecord.setForeground(Color.GRAY);
        closeLb.setForeground(Color.GRAY);
        /*
        panelMap.put("view", );
        panelMap.put("record", );
        panelMap.put("document", );
        */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        closeLb = new javax.swing.JLabel();
        lbCreate = new javax.swing.JLabel();
        lbView = new javax.swing.JLabel();
        lbRecord = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        rightPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 900));

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setDividerLocation(430);

        leftPanel.setBackground(new java.awt.Color(54, 33, 89));

        closeLb.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        closeLb.setForeground(new java.awt.Color(255, 255, 255));
        closeLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Close_Window_64px.png"))); // NOI18N
        closeLb.setText("       Log Out");
        closeLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLbMouseClicked(evt);
            }
        });

        lbCreate.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        lbCreate.setForeground(new java.awt.Color(255, 255, 255));
        lbCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Resume_64px.png"))); // NOI18N
        lbCreate.setText("       Profile");
        lbCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProfileMouseClicked(evt);
            }
        });

        lbView.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        lbView.setForeground(new java.awt.Color(255, 255, 255));
        lbView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Organization_64px.png"))); // NOI18N
        lbView.setText("       Find Jobs");
        lbView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEnterpriseMouseClicked(evt);
            }
        });

        lbRecord.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        lbRecord.setForeground(new java.awt.Color(255, 255, 255));
        lbRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Submit_Resume_64px.png"))); // NOI18N
        lbRecord.setText("       Application");
        lbRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbApplicationMouseClicked(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("<Name>");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome, ");

        areaLabel.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        areaLabel.setForeground(new java.awt.Color(255, 255, 255));
        areaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaLabel.setText("<Area>");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("in ");

        typeLabel.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("<Type>");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(leftPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel))
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(closeLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                                .addComponent(lbView, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(areaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lbCreate)
                .addGap(48, 48, 48)
                .addComponent(lbView)
                .addGap(42, 42, 42)
                .addComponent(lbRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(closeLb)
                .addGap(70, 70, 70))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rightPanel1Layout = new javax.swing.GroupLayout(rightPanel1);
        rightPanel1.setLayout(rightPanel1Layout);
        rightPanel1Layout.setHorizontalGroup(
            rightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        rightPanel1Layout.setVerticalGroup(
            rightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(rightPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbApplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbApplicationMouseClicked
        // TODO add your handling code here:
        //        createVitalSign = new CreateVitalSign(patientList);
        //        jSplitPane1.setRightComponent(createVitalSign);
        ApplicationMainJPanel applicationJPanel = new ApplicationMainJPanel(system, account, account.getRole());
        jSplitPane1.setRightComponent(applicationJPanel);
        
        lbCreate.setForeground(Color.GRAY);
        lbView.setForeground(Color.GRAY);
        lbRecord.setForeground(Color.WHITE);
        closeLb.setForeground(Color.GRAY);
    }//GEN-LAST:event_lbApplicationMouseClicked

    private void lbEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEnterpriseMouseClicked
        // TODO add your handling code here:
        //        viewPanel = new ViewPanel(patientList);
        //        jSplitPane1.setRightComponent(viewPanel);
        EnterpriseJPanel enterpriseJPanel = new EnterpriseJPanel(system, net, account, type, account.getRole());
        jSplitPane1.setRightComponent(enterpriseJPanel);

        lbCreate.setForeground(Color.GRAY);
        lbView.setForeground(Color.WHITE);
        lbRecord.setForeground(Color.GRAY);
        closeLb.setForeground(Color.GRAY);
    }//GEN-LAST:event_lbEnterpriseMouseClicked

    private void lbProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProfileMouseClicked
        // TODO add your handling code here:
        ApplicantProfileJPanel profileJPanel = new ApplicantProfileJPanel(system, account, account.getRole());
        jSplitPane1.setRightComponent(profileJPanel);
        
        lbCreate.setForeground(Color.WHITE);
        lbView.setForeground(Color.GRAY);
        lbRecord.setForeground(Color.GRAY);
        closeLb.setForeground(Color.GRAY);
    }//GEN-LAST:event_lbProfileMouseClicked

    private void closeLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLbMouseClicked
        // TODO add your handling code here:
        LoginJFrame lf = new LoginJFrame();
        this.dispose();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
        
        //System.exit(0);
    }//GEN-LAST:event_closeLbMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel closeLb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbCreate;
    private javax.swing.JLabel lbRecord;
    private javax.swing.JLabel lbView;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel rightPanel1;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
