/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Applicant;

import Business.Account.Account;
import Business.Account.ApplicantAccount;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Resume.Resume;
import Business.Role.Role;
import javax.swing.JOptionPane;

/**
 *
 * @author 11638
 */
public class ResumeJPanel extends javax.swing.JPanel {

    EcoSystem system;
    ApplicantAccount account;
    Resume resume;
    
    /**
     * Creates new form ResumeJPanel
     */
    public ResumeJPanel(EcoSystem system, ApplicantAccount account, Role accessRole) {
        initComponents();
        this.system = system;
        this.account = account;
        resume = account.getApplicant().getResume();
        setFieldsEditable(false);
        setInfo();
        saveButton.setEnabled(false);
        cancelButton.setEnabled(false);
        editButton.setEnabled(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        schoolTF = new javax.swing.JTextField();
        degreeTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        skilldescriptionTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        companyTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        workdescriptionTF = new javax.swing.JTextField();
        gpaTF = new javax.swing.JTextField();
        positionTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        skillTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        editButton.setBackground(new java.awt.Color(36, 193, 93));
        editButton.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        editButton.setForeground(new java.awt.Color(0, 51, 51));
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel16.setText("School:");

        cancelButton.setBackground(new java.awt.Color(36, 193, 93));
        cancelButton.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 51, 51));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(36, 193, 93));
        saveButton.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 51, 51));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        schoolTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        degreeTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel18.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel18.setText("Degree:");

        skilldescriptionTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel19.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel19.setText("Description:");

        jLabel20.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel20.setText("Company:");

        companyTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel21.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel21.setText("GPA:");

        jLabel22.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel22.setText("Description:");

        workdescriptionTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        gpaTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        positionTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel23.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel23.setText("Position:");

        skillTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel24.setFont(new java.awt.Font("微软雅黑", 0, 25)); // NOI18N
        jLabel24.setText("Skill:");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Work_64px_2.png"))); // NOI18N
        jLabel5.setText("Work Experience");

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(54, 33, 89));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Atom_Editor_64px_1.png"))); // NOI18N
        jLabel6.setText("Skill");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 33, 89));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Student_Male_64px_2.png"))); // NOI18N
        jLabel7.setText("Education");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(schoolTF))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(degreeTF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(positionTF)
                                        .addComponent(companyTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(workdescriptionTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(22, 22, 22))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(28, 28, 28)
                                .addComponent(skillTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(skilldescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(621, 621, 621))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(schoolTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(degreeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel23))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(companyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(128, 128, 128)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workdescriptionTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(skillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(skilldescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        saveButton.setEnabled(true);
        cancelButton.setEnabled(true);
        editButton.setEnabled(false);

        setFieldsEditable(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if ( !companyTF.getText().equals("") &&
            !degreeTF.getText().equals("") && 
            !gpaTF.getText().equals("") && 
            !positionTF.getText().equals("") &&
            !skillTF.getText().equals("") &&
            !schoolTF.getText().equals("") && 
            !skilldescriptionTF.getText().equals("") &&
            !workdescriptionTF.getText().equals("")) {
            resume.getProjectExperienceResume().setCompany(companyTF.getText());
            resume.getEducationResume().setDegree(degreeTF.getText());
            resume.getEducationResume().setGPA(gpaTF.getText());
            resume.getProjectExperienceResume().setPostion(positionTF.getText());
            resume.getSkillsResume().setSkill(skillTF.getText());
            resume.getEducationResume().setSchool(schoolTF.getText());
            resume.getSkillsResume().setDescription(skilldescriptionTF.getText());
            resume.getProjectExperienceResume().setDescription(workdescriptionTF.getText());            

        } else {
            JOptionPane.showMessageDialog(null, "Information can't be empty");
            return;        
        }
        
        setInfo();
        setFieldsEditable(false);
        saveButton.setEnabled(false);
        cancelButton.setEnabled(false);
        editButton.setEnabled(true);

        DB4OUtil.getInstance().storeSystem(system);
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setFieldsEditable(false);
        setInfo();

        saveButton.setEnabled(false);
        cancelButton.setEnabled(false);
        editButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void setInfo() {
        companyTF.setText(resume.getProjectExperienceResume().getCompany());
        degreeTF.setText(resume.getEducationResume().getDegree());
        gpaTF.setText(resume.getEducationResume().getGPA());
        positionTF.setText(resume.getProjectExperienceResume().getPostion());
        skillTF.setText(resume.getSkillsResume().getSkill());
        schoolTF.setText(resume.getEducationResume().getSchool());
        skilldescriptionTF.setText(resume.getSkillsResume().getDescription());
        workdescriptionTF.setText(resume.getProjectExperienceResume().getDescription());
    }
    
    private void setFieldsEditable(boolean b) {
        companyTF.setEnabled(b);
        degreeTF.setEnabled(b);
        gpaTF.setEnabled(b);
        positionTF.setEnabled(b);
        skillTF.setEnabled(b);
        schoolTF.setEnabled(b);
        skilldescriptionTF.setEnabled(b);
        workdescriptionTF.setEnabled(b);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField companyTF;
    private javax.swing.JTextField degreeTF;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField gpaTF;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField positionTF;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField schoolTF;
    private javax.swing.JTextField skillTF;
    private javax.swing.JTextField skilldescriptionTF;
    private javax.swing.JTextField workdescriptionTF;
    // End of variables declaration//GEN-END:variables
}
